### ISSUE TITLE
Support Spanish Validation Exam 

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/spanish-placement-exam-python#16]
Need to support sending the Spanish validation test scores set up as a separate canvas site. 

The API is going to change to specific whether sending placement and validation scores
SpanishPlacementScores/UniqName/{UniqName}/Score/{Score}/FormType/{FormType}

**Comment by pushyamig** [comment]
@ccrouch18 I need a canvas test instance course site for querying validation scores. After that I want a few users talking testing

**Comment by ccrouch18** [comment]
I made a copy of the Spanish Validation test in umich.test.instructure.com and added 3 test accounts to the course.  
https://umich.test.instructure.com/courses/351308

I added 3 students and gave them multiple extra attempts at taking the quiz:
newstuda
newstudb
newstudc

**Comment by ccrouch18** [comment]
I'm meeting with the Spanish Placement support team (LSA, Spanish, Mpathways, and Registrars Office) Wednesday.  I hope I can give them an update on this development at that meeting.  

Thanks,

**Comment by pushyamig** [comment]
@ccrouch18 can you give me the assignment name you used to take test in that course. I see quiet a few assignments in that course

**Comment by pushyamig** [comment]
Test Plan:
Course: Assignment pair: placement {"159923":267254} validation {"351308": "779517"}
1. we have scores from Spanish placement and Validation.
2. We have scores from Spanish Placement and not from Validation.
3. We have scores from Spanish not from Placement and but from Validation
4. We have no scores from either.
5. Take a test for Spanish validation/placement script to pick up scores right from their 
     this is validating the stored query date.
6. Fail in sending scores, this will test script stops with the first failure and picks up after that stored query date.
7. Check for the stored date is picked up correctly for both validation/placement 
8. Check the email report reflects what is tested.
9. Check email only sent if there are scores either in placement and validation. 
10. Check script is running the intended schedule time since email report won't be the way to do this need to check OpenShift logs.
11. check with Mpathways team they are receiving both the placement and validation scores.
