### ISSUE TITLE
Add Dockerfile (and start script) to project so we can run this on Openshift

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/spanish-placement-exam-python#3]
You should be able to re-use the Dockerfile from 

https://github.com/tl-its-umich-edu/unizin-sis-validation/blob/master/Dockerfile

and start script
https://github.com/tl-its-umich-edu/unizin-sis-validation/blob/master/start.sh

Just might have to update the dependencies. If you use the API Util currently you'll have to add these lines to the Dockerfile.

```
# Use this tag of API Utils, this will eventually be released
ENV API_UTILS_VERSION v1.1
RUN git clone https://github.com/tl-its-umich-edu/api-utils-python && cd api-utils-python && git checkout tags/${API_UTILS_VERSION} && pip install .
```

**Comment by pushyamig** [comment]
Ya, once I have the barebone requirement met then I will do the docker setup and get going. Thanks for the suggestions
